"""Agent core — provider-agnostic types and interfaces."""

from core.errors import (
    AuthenticationError,
    InvalidRequestError,
    ProviderError,
    ProviderUnavailableError,
    RateLimitError,
)
from core.messages import (
    ChatRequest,
    ChatResponse,
    ComputerUseTool,
    ContentBlock,
    ImageBlock,
    Message,
    MessageStop,
    Role,
    StopReason,
    StreamEvent,
    TextBlock,
    TextDelta,
    Tool,
    ToolResultBlock,
    ToolUseBlock,
    ToolUseDelta,
    ToolUseStart,
    Usage,
)
from core.policy import CostBudget, RoutingMode, RoutingPolicy
from core.privacy import PIIKind, PIIMatch, detect_pii, detect_pii_in_messages
from core.provider import ModelInfo, Provider, ProviderCapabilities
from core.router import (
    NoProviderAvailableError,
    Router,
    RoutingCandidate,
    RoutingDecision,
)
from core.task_classifier import TaskHints, TaskKind, TaskProfile, classify

__all__ = [
    "AuthenticationError",
    "ChatRequest",
    "ChatResponse",
    "ComputerUseTool",
    "ContentBlock",
    "CostBudget",
    "ImageBlock",
    "InvalidRequestError",
    "Message",
    "MessageStop",
    "ModelInfo",
    "NoProviderAvailableError",
    "PIIKind",
    "PIIMatch",
    "Provider",
    "ProviderCapabilities",
    "ProviderError",
    "ProviderUnavailableError",
    "RateLimitError",
    "Role",
    "Router",
    "RoutingCandidate",
    "RoutingDecision",
    "RoutingMode",
    "RoutingPolicy",
    "StopReason",
    "StreamEvent",
    "TaskHints",
    "TaskKind",
    "TaskProfile",
    "TextBlock",
    "TextDelta",
    "Tool",
    "ToolResultBlock",
    "ToolUseBlock",
    "ToolUseDelta",
    "ToolUseStart",
    "Usage",
    "classify",
    "detect_pii",
    "detect_pii_in_messages",
]
